version: '3.7'
services:
  web:
    build: .
    command: bash -c "python3 int_handler.py"
    volumes:
      - .:/usr/src/TornadoApp
    ports:
      - 8888:8888
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:12.1-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=array_db
volumes:
  postgres_data:
