"""empty message

Revision ID: 0ce659ab1778
Revises: 
Create Date: 2021-10-20 14:20:36.845001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ce659ab1778'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('array',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('array', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('result_array', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('date_of_creation', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('array')
    # ### end Alembic commands ###
